// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBevDwFQwHI0QVcIXz0o-pE47ltJR49Ipo',
    appId: '1:485496820758:web:f992cc9fd82236d7045137',
    messagingSenderId: '485496820758',
    projectId: 'saloon-b8b5c',
    authDomain: 'saloon-b8b5c.firebaseapp.com',
    storageBucket: 'saloon-b8b5c.appspot.com',
    measurementId: 'G-PKFSLMGYHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkLNFL54lGHben7UR26GG-754IQ9N5eLw',
    appId: '1:485496820758:android:39c9363ad50e3b4d045137',
    messagingSenderId: '485496820758',
    projectId: 'saloon-b8b5c',
    storageBucket: 'saloon-b8b5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdL3Ko_mhFm6PUFmR9m_TybQRXB9lS3Zg',
    appId: '1:485496820758:ios:0faf30aa6771b24d045137',
    messagingSenderId: '485496820758',
    projectId: 'saloon-b8b5c',
    storageBucket: 'saloon-b8b5c.appspot.com',
    iosBundleId: 'com.example.estiloSalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdL3Ko_mhFm6PUFmR9m_TybQRXB9lS3Zg',
    appId: '1:485496820758:ios:83cf35bac3ac3460045137',
    messagingSenderId: '485496820758',
    projectId: 'saloon-b8b5c',
    storageBucket: 'saloon-b8b5c.appspot.com',
    iosBundleId: 'com.example.estiloSalon.RunnerTests',
  );
}
